# Adapted from https://github.com/vercel/next.js/tree/canary/examples/with-docker

services:
  # Node.js service (use with: docker compose up transition-site --build)
  transition-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: transition-site-image
    container_name: transition-site-container
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
