name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-lint-build:
    name: Style, Lint, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm prettier --check .
        continue-on-error: true

      - name: Run ESLint
        run: pnpm lint
        continue-on-error: true

      - name: Build the project
        run: pnpm build
